spring.application.name=ECommerceWebApplication

#spring.datasource.url=jdbc:mysql://lifestyle.cvqkuako4xoy.eu-north-1.rds.amazonaws.com:3306/ecommerce
#spring.datasource.username=admin
#spring.datasource.password=Admin1234
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.username=kr2235520@gmail.com
#spring.mail.password=ulmsjulnwtfupfzi
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.logo.url=https://res.cloudinary.com/dyqsgxe3q/image/upload/f_auto,q_auto/logo_g3ahaq
#app.frontend.url=http://localhost:5173
app.frontend.url=${FRONTEND_URL}
app.company.name=LIFESTYLE
app.support.email=support@lifestyle.com
app.admin.email=kr2235520@gmail.com
server.port=${PORT:8080}
#server.port=${PORT}
#server.address=0.0.0.0

#razorpay.key.id=rzp_test_STLOAdtz22xShu
#razorpay.key.secret=1L6V5TseC6HXo3D4awIADX9B
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

#spring.security.user.name=
#spring.security.user.password=
